// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewProject struct {
	ProjectName string `json:"project_name"`
	OwnedBy     string `json:"owned_by"`
}

type Project struct {
	ID          string `json:"id"`
	CreatedDate string `json:"created_date"`
	LastEdited  string `json:"last_edited"`
	ProjectName string `json:"project_name"`
	OwnedBy     *User  `json:"owned_by"`
}

type Query struct {
}

type User struct {
	ID       string `json:"id"`
	Email    string `json:"email"`
	UserName string `json:"user_name"`
}
