// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type File struct {
	ID        string   `json:"id"`
	Name      string   `json:"name"`
	Type      FileType `json:"type"`
	Content   string   `json:"content"`
	Project   *Project `json:"project"`
	CreatedAt string   `json:"createdAt"`
	UpdatedAt string   `json:"updatedAt"`
}

type Mutation struct {
}

type NewFile struct {
	ProjectID string   `json:"projectId"`
	Name      string   `json:"name"`
	Type      FileType `json:"type"`
}

type NewProject struct {
	ProjectName string `json:"projectName"`
	OwnedBy     string `json:"ownedBy"`
}

type NewUser struct {
	Email    string `json:"email"`
	UserName string `json:"userName"`
}

type Project struct {
	ID            string     `json:"id"`
	CreatedDate   string     `json:"createdDate"`
	LastEdited    string     `json:"lastEdited"`
	ProjectName   string     `json:"projectName"`
	OwnedBy       *User      `json:"ownedBy"`
	Collaborators []*User    `json:"collaborators"`
	RootFile      *File      `json:"rootFile"`
	Files         []*File    `json:"files"`
	Versions      []*Version `json:"versions"`
}

type Query struct {
}

type Subscription struct {
}

type User struct {
	ID             string     `json:"id"`
	Email          string     `json:"email"`
	UserName       string     `json:"userName"`
	Projects       []*Project `json:"projects"`
	Collaborations []*Project `json:"collaborations"`
}

type Version struct {
	ID        string         `json:"id"`
	Project   *Project       `json:"project"`
	CreatedAt string         `json:"createdAt"`
	Message   *string        `json:"message,omitempty"`
	Files     []*VersionFile `json:"files"`
}

type VersionFile struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	Content string `json:"content"`
}

type FileType string

const (
	FileTypeTex   FileType = "TEX"
	FileTypeBib   FileType = "BIB"
	FileTypeImage FileType = "IMAGE"
	FileTypeCls   FileType = "CLS"
	FileTypeSty   FileType = "STY"
	FileTypeOther FileType = "OTHER"
)

var AllFileType = []FileType{
	FileTypeTex,
	FileTypeBib,
	FileTypeImage,
	FileTypeCls,
	FileTypeSty,
	FileTypeOther,
}

func (e FileType) IsValid() bool {
	switch e {
	case FileTypeTex, FileTypeBib, FileTypeImage, FileTypeCls, FileTypeSty, FileTypeOther:
		return true
	}
	return false
}

func (e FileType) String() string {
	return string(e)
}

func (e *FileType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FileType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FileType", str)
	}
	return nil
}

func (e FileType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *FileType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e FileType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
