// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type CreateVersionInput struct {
	ProjectID string  `json:"projectId"`
	Message   *string `json:"message,omitempty"`
}

type File struct {
	ID          string       `json:"id"`
	ProjectID   string       `json:"projectId"`
	Name        string       `json:"name"`
	Type        FileType     `json:"type"`
	CreatedAt   string       `json:"createdAt"`
	UpdatedAt   string       `json:"updatedAt"`
	WorkingFile *WorkingFile `json:"workingFile"`
}

type Mutation struct {
}

type NewFileInput struct {
	ProjectID string   `json:"projectId"`
	Name      string   `json:"name"`
	Type      FileType `json:"type"`
}

type NewProjectInput struct {
	ProjectName string `json:"projectName"`
}

type Project struct {
	ID              string     `json:"id"`
	ProjectName     string     `json:"projectName"`
	CreatedAt       string     `json:"createdAt"`
	LastEditedAt    string     `json:"lastEditedAt"`
	OwnerID         string     `json:"ownerId"`
	CollaboratorIds []string   `json:"collaboratorIds"`
	RootFileID      string     `json:"rootFileId"`
	Files           []*File    `json:"files"`
	Versions        []*Version `json:"versions"`
}

type Query struct {
}

type Subscription struct {
}

type UpdateWorkingFileInput struct {
	FileID  string `json:"fileId"`
	Content string `json:"content"`
}

type User struct {
	ID          string `json:"id"`
	ClerkUserID string `json:"clerkUserId"`
	CreatedAt   string `json:"createdAt"`
}

type Version struct {
	ID        string         `json:"id"`
	ProjectID string         `json:"projectId"`
	CreatedAt string         `json:"createdAt"`
	Message   *string        `json:"message,omitempty"`
	Files     []*VersionFile `json:"files"`
}

type VersionFile struct {
	ID        string   `json:"id"`
	VersionID string   `json:"versionId"`
	FileID    string   `json:"fileId"`
	Name      string   `json:"name"`
	Type      FileType `json:"type"`
	Content   string   `json:"content"`
}

type WorkingFile struct {
	ID        string `json:"id"`
	FileID    string `json:"fileId"`
	ProjectID string `json:"projectId"`
	Content   string `json:"content"`
	UpdatedAt string `json:"updatedAt"`
}

type FileType string

const (
	FileTypeTex   FileType = "TEX"
	FileTypeBib   FileType = "BIB"
	FileTypeImage FileType = "IMAGE"
	FileTypeCls   FileType = "CLS"
	FileTypeSty   FileType = "STY"
	FileTypeOther FileType = "OTHER"
)

var AllFileType = []FileType{
	FileTypeTex,
	FileTypeBib,
	FileTypeImage,
	FileTypeCls,
	FileTypeSty,
	FileTypeOther,
}

func (e FileType) IsValid() bool {
	switch e {
	case FileTypeTex, FileTypeBib, FileTypeImage, FileTypeCls, FileTypeSty, FileTypeOther:
		return true
	}
	return false
}

func (e FileType) String() string {
	return string(e)
}

func (e *FileType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FileType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FileType", str)
	}
	return nil
}

func (e FileType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *FileType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e FileType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
